name: Regression Tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  regression:
    name: Run Regression Tests
    runs-on: ubuntu-latest

    steps:
      - name: Trigger automation repository
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.AUTOMATION_REPO_TOKEN }}
          repository: https://github.com/vanshika-nahar/nextjs-demo-automation
          event-type: run-regression-tests