name: Smoke Tests

on:
  pull_request:
    branches:
      - stage
    types:
      - opened
      - synchronize
      - reopened

jobs:
  smoke-tests:
    name: Run Smoke Tests
    if: github.event.pull_request.base.ref == 'stage' && github.event.pull_request.head.ref == 'dev'
    uses: https://github.com/Surety007/automation-testing/.github/workflows/smoke-tests.yml@main
    secrets: inherit